### ISSUE TITLE
Study Rooms Unknown Error

### ISSUE THREAD

**Issue by Aevyz** [TUM-Dev/Campus-Android#1350] opened 2020-01-09 20:37 UTC
## Steps to Reproduce

1. Open App
2. Hit Study Rooms
3. Get Unknown Error

## Expected Result

Study Rooms

## Actual Result

No Study Rooms

## Problem

No study rooms show up, instead you get an `Unknown Error`

## Suggested Enhancement :sparkles:

Change Unknown Error to an Error that is specified or show the rooms :)

### Environment

Tested on a second phone as well

* Phone: Xiao Mi A3
* OS version: 9
* TUM Campus App version: v3.4
* Language: English

**Comment by Aevyz** [comment] 2020-01-09 20:37
Tested on Eduroam and Mobile Data. Also IRIS is not down right now

**Comment by Bentipa** [comment] 2022-07-19 15:06
I can't reproduce this issue.
It seems like if no network connection is available, the unknown error is shown.
But currently it is just shown if an error occurs during the loading of data, which actually then is unknown where it comes from.

I would close this for now, either we make a global "Offline Error" system (via a separate ticket) or we find another occurrence of this bug.

**Closed by Bentipa** 2022-07-19 15:06 UTC
Labels: Bug :bug:
