### ISSUE TITLE
Cafeteria Selection: NPE on population of fields

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1282] opened 2019-04-12 06:58 UTC
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void androidx.preference.MultiSelectListPreference.setEntries(java.lang.CharSequence[])'on a null object reference

de.tum.in.tumcampusapp.component.other.settings.SettingsFragment.initCafeteriaCardSelections (SettingsFragment.java:129)
de.tum.in.tumcampusapp.component.other.settings.SettingsFragment.onCreatePreferences (SettingsFragment.java:68)
androidx.preference.PreferenceFragmentCompat.onCreate (PreferenceFragmentCompat.java:228)
```

https://console.firebase.google.com/u/0/project/tca-backend-0001/crashlytics/app/android:de.tum.in.tumcampus/issues/5c9621d3f8b88c2963449e89

**Comment by jacqueline8711** [comment] 2019-04-21 09:43
Duplicate of #1284

**Closed by jacqueline8711** 2019-04-21 09:43 UTC
Labels: Bug :bug:, Duplicate
