### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: Unknown XmlToken: Peeked = 0

### ISSUE THREAD

**Issue by TG908** [TUM-Dev/Campus-Android#1355] opened 2020-09-17 16:44 UTC
```
Fatal Exception: java.lang.AssertionError: Unknown XmlToken: Peeked = 0
       at com.tickaroo.tikxml.XmlReader.peek(XmlReader.java:142)
       at com.tickaroo.tikxml.XmlReader.beginElement(XmlReader.java:332)
       at com.tickaroo.tikxml.TikXml.read(TikXml.java:110)
       at de.tum.in.tumcampusapp.api.tumonline.interceptors.CheckErrorInterceptor.intercept(CheckErrorInterceptor.java:30)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at de.tum.in.tumcampusapp.api.tumonline.interceptors.CacheResponseInterceptor.intercept(CacheResponseInterceptor.java:12)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at de.tum.in.tumcampusapp.api.app.TumHttpLoggingInterceptor.intercept(TumHttpLoggingInterceptor.java:115)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at de.tum.in.tumcampusapp.api.tumonline.interceptors.CheckTokenInterceptor.intercept(CheckTokenInterceptor.java:28)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at de.tum.in.tumcampusapp.api.tumonline.interceptors.AddTokenInterceptor.intercept(AddTokenInterceptor.java:37)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at de.tum.in.tumcampusapp.api.app.ApiHelper.lambda$getDeviceInterceptor$1(ApiHelper.java:112)
       at de.tum.in.tumcampusapp.api.app.-$$Lambda$ApiHelper$_FXkkfeQlZsROF04nffkOYNCvJY.intercept(-.java:4)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:210)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by kordianbruck** [comment] 2020-09-17 21:13
Caused by TUMonline giving us gzip stuff that somehow didn't decode. Didn't look further into it. Fixed in https://github.com/TUM-Dev/Campus-Android/commit/29f99c93236feebd4defaac5a09025d2ae138602 and released with 3.5

**Closed by kordianbruck** 2020-09-17 21:13 UTC
