### ISSUE TITLE
[BUG] App crashing on startup

### ISSUE THREAD

**Issue by XSpielinbox** [TUM-Dev/Campus-Android#1520] opened 2022-10-22 10:24 UTC
**Describe the bug**
The app repeatedly crashes on startup. Restarting the phone, clearing the app-cache or reinstalling the app does not help.

**To Reproduce**
1. Click on the App from the home screen or app launcher

**Expected behavior**
The App starts and I can use it.

**Screenshots**
Sometimes it is only a black screen, before the app crashes, sometimes the loading screen appears, sometimes a system dialog appears that the app is not responding (neither waiting nor forcing an app close helps).

**Smartphone (please complete the following information):**
* Phone: Fairphone 4 as well as Samsung Galaxy A6+
* OS version: Android 10 as well as /e/OS 1.4 (Android 11)
* Language (OS): English

**Additional context**
It worked on both devices for a few days then it broke, for a few days it worked again and since half a year it is again broken.
When a notification shows up, clicking on the notification shows the according app-part without problem, but when then trying to navigate to a different part of the app it crashes again.

**Comment by kordianbruck** [comment] 2022-11-04 11:50
You have a stack trace by any chance? Whcih escat version of the App?

**Comment by XSpielinbox** [comment] 2022-11-13 16:20
Sorry for the late reply.
What is the "escat version"? How to I check it? It happened on all versions of the app released in the last year or so, incl. 4.0-beta1. For a short time this spring it worked, but then suddenly broke again (though as far as I remember it broke while staying on the same version of the app).

How do I see the stack trace or generate it on Android?
I tried the "bug report" feature from the developer settings but the resulting txt and zip files seem like having low informational value to this problem as I can't find any Exception linked to this app. If you are interested in what I could generate anyway I could send that.
I also tried getting the log via adb and USB-Debugging but it wouldn't recognize the device. When running `adb devices` it would recognize the device but only with "no permission".

**Comment by CommanderStorm** [comment] 2022-11-13 16:48
Even though they might have low informational content, they might still be useful.

Honestly, I can't get this to crash with settings as close to Fairphone as possible.
It would be useful for us, if you were to either generate it via the feature you mentioned, or you can run the app on your phone using android studio and get a live log view by launching here (assuming, you have set it your device up in the device manager):
![image](https://user-images.githubusercontent.com/26258709/201533315-c5e644f7-b29f-428f-b2fd-e2a0c9e9b55a.png)


Just a wild guess:
Does Fairphone have Google services installed? (we use those for notifications, and othe essential stuff)

**Comment by XSpielinbox** [comment] 2022-11-14 09:07
/e/ OS (what I have installed on my Fairphone 4 at the moment) does not use Google Services Framework but MicroG as an open source replacement instead. As stated, the notifications and the part of the app of the notification works, but switching to other parts or starting the app normally does not.
Also, I also had the problem on  the Samsung version of Android (which uses GSF) on my old phone for some time. So the problem may relate to a insufficient compatibility with MicroG but there must be something else too.

I will send you the information as soon as I had time to prepare the bug report and could try setting up Android Studio.

**Comment by XSpielinbox** [comment] 2022-12-31 13:20
I finally found some time to try to get some debug output:
When I attach a debugger from Android Studio to the Process of `de.tum.in.tumcampus` and configure on my device that it shall not start the app, before the debugger is attached and I then open the App on my phone.
`Connected to the target VM, address: 'localhost:46367', transport: 'socket'` is shown in the debug console in Android Studio, then the loading screen of the app appears shortly on my phone, before it crashes, only leaving a `Disconnected from the target VM, address: 'localhost:46367', transport: 'socket'` behind in the debugger console.

**Comment by XSpielinbox** [comment] 2022-12-31 14:55
When downloading the Tag 4.0 zip file (though it reports it's version as 4.1-dev), unpacking it and running the application on my phone after uninstalling the normally installed one it starts up normally (though of course I am not logged in anymore). 
However, a memory leak is shown, here the heap dump analysis:
[HEAP ANALYSIS RESULT_blackened.txt](https://github.com/TUM-Dev/Campus-Android/files/10327467/HEAP.ANALYSIS.RESULT_blackened.txt)
I have not attached the .hprof heap dump file, as I am unsure, whether it contains sensitive data.

When searching where to find the "Logcat" where one could print the heap analysis to, I found a view in Android Studio with the following content:
[logcat_blackened.txt](https://github.com/TUM-Dev/Campus-Android/files/10327463/logcat_blackened.txt)
According to the timestamps I would assume that this is where the relevant errors of the crash where logged to:
Everything before 14:20 must be from the latest version from the Aurora Store (Version 4.0 from the 16.11.2022, as it is in the Play Store too), that was crashing on startup:
```
java.lang.ClassCastException: com.google.android.play.core.internal.zzat cannot be cast to com.google.android.play.core.review.ReviewException
at de.tum.in.tumcampusapp.component.ui.overview.MainFragment.triggerReviewPrompt$lambda-2(MainFragment.kt:190)
at de.tum.in.tumcampusapp.component.ui.overview.MainFragment.$r8$lambda$m8fOp0j6HyX2ulP4M4cVAfmKVBg(Unknown Source:0)
at de.tum.in.tumcampusapp.component.ui.overview.MainFragment$$ExternalSyntheticLambda0.onComplete(Unknown Source:4)
```
Everything after 14:40 must be from the Version downloaded as a zip from GitHub.

By the way: When opening the project in Android Studio I get a lot of warnings that
* [ ] `com.android.tools.build:gradle`
* [ ] `com.google.gms:google-services`
* [ ] `org.jetbrains.kotlin:kotlin-gradle-plugin`
* [ ] `com.google.firebase:firebase-crashlytics-gradle`
* [ ] `targetSdkVersion`
* [ ] `com.google.android.material:material`
* [ ] `androidx.room:room-rxjava2`
* [ ] `androidx.room:room-runtime`
* [ ] `androidx.lifecycle:lifecycle-runtime-ktx`
* [ ] `androidx.appcompat:appcompat`
* [ ] `androidx.lifecycle:lifecycle-common-java8`
* [ ] `com.google.android.gms:play-services-base`
* [ ] `com.google.android.gms:play-services-location`
* [ ] `com.google.firebase:firebase-core`
* [ ] `com.google.firebase:firebase-messaging`
* [ ] `com.google.firebase:firebase-crashlytics-ktx`
* [ ] `com.google.firebase:firebase-analytics-ktx`
* [ ] `org.jetbrains.kotlin:kotlin-stdlib-jdk8`
* [ ] `androidx.core:core-ktx`
* [ ] `androidx.fragment:fragment-ktx`
* [ ] `androidx.test:core`
* [ ] `androidx.room:room-testing`
have newer versions available and it is recommended to update them.

P.S. I have redacted the mentioned keys as they seemed sensitive to me.

**Comment by XSpielinbox** [comment] 2022-12-31 15:22
When then again uninstalling that dev version and installing the latest release, I noticed that it still does not crash on startup. So perhaps the error seems to be dependent on something in app storage, perhaps the login data or data retrieved/stored only when logged in?

I have attached the further Logcat output, again with redacted ids:
[logcat-part2_blackened.txt](https://github.com/TUM-Dev/Campus-Android/files/10327552/logcat-part2_blackened.txt)

I thereby also noticed that the app makes connections to 3 subdomains of 1e100.net (Google services) WITHOUT any user consent. As the app includes tracking services Google CrashLytics and Google Firebase Analytics, which I find highly problematic anyway, I highly question whether these are really essential for the functionality of the app. After all a meaningful user consent is necessary to connect to these services, see e.g. [here](https://www.kuketz-blog.de/untis-mobile-app-ungefragte-uebermittlung-zu-google-crashlytics/) or [here](https://www.kuketz-blog.de/e-rezept-website-trackt-mit-google-analytics-widerspruch-wirkungslos/).

**Comment by CommanderStorm** [comment] 2022-12-31 22:31
> from the Aurora Store
We do not explicitly provide support to external stores like F-Droid or Aurora.
The effort required is not something we can't provide.
There be dragons.

> When opening the project in Android Studio I get a lot of warnings

Yea…
Keeping everything updated is always a considerable undertaking as there are a lot of suttle things that will break and there are migration guides that need to be followed for every one of those services.
If you want to chip in, any effort on this side is greatly appreciated.
If you do chip in, keep in mind, that one PR should migrate one dependency/class of dependencies whichever is better for reviewability.
Tbh: Corona has not been gentle on our team-size, and we are currently struggling a lot. (as can be seen in the PR-Tab)

> `java.lang.ClassCastException: com.google.android.play.core.internal.zzat cannot be cast to com.google.android.play.core.review.ReviewException`

It seems like a duplicate of https://github.com/TUM-Dev/Campus-Android/issues/1531
I am closing this because of this. If you think differently, feel free to bump this issue. 

I have contacted some privacy experts on our team about your privacy concerns.  
They will get back to you.

**Closed by CommanderStorm** 2022-12-31 22:31 UTC
Labels: Bug :bug:, Awaiting more Information :hourglass:

**Comment by XSpielinbox** [comment] 2023-01-01 20:48
> We do not explicitly provide support to external stores like F-Droid or Aurora.

Yes, I somewhat expected that. As long as the app does not rely on GSF, this isn't any issue though. Aurora Store ships the same binaries as the Play Store after all.
I also opened this issue to help improving support on that front. I would like to help out more too, but I am not into mobile development and have more than enough work on other projects to to, I unfortunately can't help much. But if you have something where you just need some degoogled device to test, I might be able to help. Just reach out to me.

> If you want to chip in, any effort on this side is greatly appreciated.

As stated above, I would highly appreciate it to see it done and would also like to help, but do not have the time.

> It seems like a duplicate of #1531
> If you think differently, feel free to bump this issue.

Ah, thanks. I have left an comment under the corresponding PR.
